### ISSUE TITLE
SQL Server SQL Login Password Settings

### ISSUE THREAD

**Issue by mhiett** [azauditor/SQLAudit#1]
@AZphanus Recommend removing the line noted below including the comma above the line.
**"**,
    '[INSERT NUMBER OF DAYS THAT PASSWORD ARE SUPPOSED TO EXPIRE]' - DATEDIFF(DAY, CONVERT(DATETIME, LOGINPROPERTY(name, 'PasswordLastSetTime')), GETDATE()) AS 'DaysUntilExpiration'**"**

**Comment by IntenseLee1995** [comment]
@AZphanus, I recommend only requesting two columns; is_policy_checked and is_expiration_checked.

SELECT name AS 'SQL_User',
    is_policy_checked AS 'EnforcePasswordPolicyChecked', 
    is_expiration_checked AS 'EnforcePasswordExpirationChecked'
FROM sys.sql_logins

**Comment by AZphanus** [comment]
Updated query with the requested changes.

**Comment by kmorris77** [comment]
@AZphanus Recommend removing the GROUP BY line in the "SQL Server SQL Login Password Settings" query as the following error occurs: 

Msg 8120, Level 16, State 1, Line 2
Column 'sys.sql_logins.is_policy_checked' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.

**Comment by AZphanus** [comment]
Updated query with the requested changes.

**Comment by AZphanus** [comment]
Updated query with the requested changes.
